import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { CartDataProvider } from "@/context/useCartDataContext";
import Header from "@/components/Header";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Audiophile Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.className} text-base text-primary-color min-h-svh flex flex-col`}
      >
        <CartDataProvider>
          <div className="flex-1">
            <Header></Header>
            {children}
          </div>
        </CartDataProvider>
      </body>
    </html>
  );
}
